services:
  mysql:
    image: 'mysql:8.0'
    environment:
      - 'MYSQL_DATABASE=lesson'
      - 'MYSQL_PASSWORD=secret'
      - 'MYSQL_ROOT_PASSWORD=verysecret'
      - 'MYSQL_USER=lesson'
      - 'MYSQL_CHARACTER_SET=utf8mb4'
      - 'MYSQL_COLLATE=utf8mb4_general_ci'
    ports:
      - '3306'
