server:
  port: 8080
  shutdown: graceful

spring:
  profiles:
    active: dev

---

spring:
  config:
    activate:
      on-profile: dev
  application:
    name: lesson-test
  datasource:
    url: jdbc:mysql://localhost:3306/lesson?useSSL=false&allowPublicKeyRetrieval=true&rewriteBatchedStatements=true
    username: lesson
    password: secret
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: false
    open-in-view: false
    properties:
      hibernate.jdbc.batch_size: 1000   # 1000개 단위로 batch
      hibernate.order_inserts: true
      hibernate.order_updates: true

logging:
  level:
    org.springframework.jdbc.core.JdbcTemplate: DEBUG
    org.springframework.jdbc.core.StatementCreatorUtils: TRACE
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.batch: TRACE

decorator:
  datasource:
    p6spy:
      enable-logging: true
      multiline: true

---

spring:
  config:
    activate:
      on-profile: test

